---
title: "关于迪基-富勒检验"
author: 王一刀
categories: [量化交易]
date: 2024-08-20
format: html
---

## 时间序列模型

时间序列模型是一种用于分析和预测时间序列数据的统计模型。这些模型通过识别数据中的趋势、季节性和其他模式，来预测未来的值。以下是关于时间序列模型的相关信息：

### 时间序列模型的定义
时间序列模型定义为一个随机过程，即**按时间排序的随机变量的集合**。每个时刻的位置点作为一个随机变量，其取值是从一个分布中采样得到的。

### 时间序列模型的分类
* 自回归模型 (AR)：根据历史观测值来预测未来时序。
* 移动平均模型 (MA)：根据白噪声的系数加权和来预测未来时序。
* 自回归移动平均模型 (ARMA)：结合了AR和MA的特点，同时考虑历史观测值和白噪声的影响。
* 差分移动自回归模型 (ARIMA)：适用于有明显上升或下降趋势的数据集，通过差分使数据平稳后使用ARMA拟合。

### 时间序列模型的平稳性
平稳性是指时间序列的统计特性（如均值、方差和自协方差）不随时间变化。如果时间序列有季节性和趋势性，则视为不平稳。平稳性是许多时间序列预测模型（如自回归模型）的基础。

### 特征根与时间序列模型的关系
特征根是判断时间序列模型平稳性的关键。一个平稳时间序列模型的特征根都在单位圆内，这意味着模型是稳定的，能够提供可靠的预测。

## 特征根
特征根是线性代数中的一个重要概念，特别是在时间序列分析中。特征根与特征向量一起，构成了理解线性变换和动态系统行为的基础。以下是关于特征根的相关信息：

### 特征根的定义
特征根是线性代数中一个矩阵的特征方程的根，它表示矩阵对应的线性变换在特定方向上的伸缩因子。在时间序列分析中，特征根与时间序列的稳定性密切相关。

### 特征根在时间序列分析中的应用
* 平稳性检验：通过检查特征根的位置（是否在单位圆内），可以判断时间序列是否平稳。如果所有特征根都在单位圆内，则时间序列是平稳的，否则是非平稳的。
* 模型选择：不同的时间序列模型（如AR、MA、ARMA）的特征根有不同的性质，这些性质可以帮助我们选择合适的模型进行分析和预测。

### 特征根与时间序列稳定性的关系
单位根与序列稳定性：如果一个时间序列的特征根包含单位根（即特征根的绝对值等于1），则该序列是非平稳的。单位根的存在意味着序列的统计特性会随时间变化，这可能会影响到时间序列的预测能力。

特征方程：对于时间序列模型，特征方程是通过将模型的差分方程转化为代数方程得到的。例如，AR(1)模型的特征方程为 1−aZ=0，其中 a 是自回归系数，Z 是特征根

对模型预测能力的影响：特征根的位置决定了时间序列模型的预测能力。平稳的时间序列模型（所有特征根都在单位圆内）可以提供可靠的短期预测，而非平稳序列可能需要通过差分等方法转换为平稳序列后才能进行有效预测。

### 特征根的理解
特征根是线性代数中的一个重要概念，它与矩阵的特征方程密切相关。特征方程是一个关于未知数λ的方程，这个方程是通过求解矩阵A减去λ倍的单位矩阵后的行列式等于0得到的。

具体来说，对于一个n×n的矩阵A，其特征方程可以表示为：
det(A - λI) = 0

其中，det表示行列式，I是n×n的单位矩阵，λ是我们要求的特征根。

这个特征方程的解，即特征根λ，具有特殊的意义。它表示矩阵A对应的线性变换在某个特定方向上的伸缩因子。换句话说，如果我们有一个向量v，它是对应于特征根λ的特征向量，那么矩阵A作用在这个向量上，就相当于把这个向量伸缩了λ倍。

举个例子来说明这个概念：

假设我们有一个2×2的矩阵A：

```
A = [[3, 1],
     [1, 3]]
```
我们需要找到这个矩阵的特征根和特征向量。

首先，我们写出特征方程：
det(A - λI) = det([[3-λ, 1],
[1, 3-λ]]) = (3-λ)^2 - 1 = λ^2 - 6λ + 8 = 0

解这个方程，我们得到两个特征根：
λ1 = 2, λ2 = 4

接下来，我们分别求对应于这两个特征根的特征向量。

对于λ1 = 2，我们解方程组(A - 2I)v = 0，得到一个特征向量v1 = [1, -1]^T（T表示转置）。

对于λ2 = 4，我们解方程组(A - 4I)v = 0，得到另一个特征向量v2 = [1, 1]^T。

现在，我们可以验证特征根的含义。对于特征向量v1 = [1, -1]^T，矩阵A作用在这个向量上得到的结果是：
Av1 = A[1, -1]^T = [3 * 1 + 1*(-1), 1 * 1 + 3*(-1)]^T = [2, -2]^T = 2*v1

可以看到，矩阵A将特征向量v1伸缩了2倍，这与我们找到的特征根λ1 = 2是一致的。

同样地，对于特征向量v2 = [1, 1]^T，矩阵A作用在这个向量上得到的结果是：
Av2 = A[1, 1]^T = [3 * 1 + 1 * 1, 1 * 1 + 3 * 1]^T = [4, 4]^T = 4*v2

矩阵A将特征向量v2伸缩了4倍，这与我们找到的特征根λ2 = 4也是一致的。

通过这个例子，我们可以看到特征根确实表示了矩阵对应的线性变换在特定方向上的伸缩因子。

In [8]:
import numpy as np
import pandas as pd
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# 定义一个2x2矩阵
A = np.array([[3, 1],
              [1, 3]])

# 使用numpy.linalg.eig函数计算特征根和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)

print("特征根:", eigenvalues)
print("特征向量:\n", eigenvectors)

# 生成一个非平稳的时间序列数据
np.random.seed(0)
data = np.cumsum(np.random.randn(100))

# 将数据转换为pandas的Series对象
data_series = pd.Series(data)

# 绘制时间序列图
# data_series.plot()

# 进行DF检验
result_df = adfuller(data_series)

# 输出DF检验结果
print('ADF Statistic:', result_df[0])
print('p-value:', result_df[1])
print('Critical Values:', result_df[4])

# 根据p-value判断是否拒绝原假设
if result_df[1] < 0.05:
    print('拒绝原假设，序列是平稳的')
else:
    print('接受原假设，序列是非平稳的')


# 进行ADF检验
result_adf = adfuller(data_series, regression='c', autolag='AIC')

# 输出ADF检验结果
print('ADF Statistic:', result_adf[0])
print('p-value:', result_adf[1])
print('Critical Values:', result_adf[4])

# 根根据p-value判断是否拒绝原假设
if result_adf[1] < 0.05:
    print('拒绝原假设，序列是平稳的')
else:
    print('接受原假设，序列是非平稳的')

# 进行KPSS检验
result_kpss = kpss(data_series, regression='c')

# 输出KPSS检验结果
print('KPSS Statistic:', result_kpss[0])
print('p-value:', result_kpss[1])
print('Critical Values:', result_kpss[3])

# 根据p-value判断是否拒绝原假设
if result_kpss[1] > 0.05:
    print('拒绝原假设，序列是平稳的')
else:
    print('接受原假设，序列是非平稳的')

特征根: [4. 2.]
特征向量:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
ADF Statistic: -1.1320384625097901
p-value: 0.7021277385898382
Critical Values: {'1%': -3.498198082189098, '5%': -2.891208211860468, '10%': -2.5825959973472097}
接受原假设，序列是非平稳的
ADF Statistic: -1.1320384625097901
p-value: 0.7021277385898382
Critical Values: {'1%': -3.498198082189098, '5%': -2.891208211860468, '10%': -2.5825959973472097}
接受原假设，序列是非平稳的
KPSS Statistic: 1.1001161286471666
p-value: 0.01
Critical Values: {'10%': 0.347, '5%': 0.463, '2.5%': 0.574, '1%': 0.739}
接受原假设，序列是非平稳的


C:\Users\win10\AppData\Local\Temp\ipykernel_15296\3430932899.py:56: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result_kpss = kpss(data_series, regression='c')


DF检验，也称为Dickey-Fuller检验，是一种用于检验时间序列数据是否含有单位根的统计方法。单位根是指一个时间序列的期望值不为零，但其自协方差函数仅依赖于时间间隔的长度，而不依赖于时间的起点。这种特性使得时间序列数据表现出非平稳性，即它们的统计特性会随时间变化。DF检验的基本思想是通过检验时间序列的回归模型中的自回归系数是否为零来确定是否存在单位根。以下是DF检验的相关信息：

### DF检验的基本原理
DF检验通过检验时间序列的回归模型中的自回归系数是否为零来确定是否存在单位根。如果自回归系数显著不为零，则表明序列含有单位根，即序列是非平稳的。

### DF检验的应用场景
DF检验广泛应用于经济学、金融学和统计学等领域，用于检验时间序列数据的平稳性。例如，在经济学中，它可以帮助分析经济增长率、通货膨胀率等时间序列数据的稳定性。

### DF检验的优缺点
优点：DF检验是一种简单且易于实施的统计方法，适用于均值比较的问题，并且可以处理样本大小不一致的情况。
缺点：DF检验对样本数据的正态性有一定要求，如果数据不符合正态分布，可能会影响检验结果的准确性。它只能比较两个样本均值之间的差异，不能提供对多个样本进行比较的信息。

### DF检验与ADF检验的区别
DF检验是最早提出的单位根检验方法之一，它是建立在一个简单的自回归模型(AR(1))上的。相比之下，ADF检验使用了更复杂的自回归模型，并且引入了趋势项来对序列的趋势进行建模，从而提高了检验的适用性和准确性。
DF检验只能应用于一阶情况，当序列存在高阶的滞后相关时，可以使用ADF检验，所以说ADF是对DF检验的扩展。

In [3]:
import statsmodels.api as sm
import numpy as np

# 假设我们有以下数据
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
print(x)
# 添加截距项
x = sm.add_constant(x)

print(x)

# 拟合线性回归模型
# model = sm.OLS(y, x).fit()

# # 输出模型摘要
# print(model.summary())

# # 预测
# predictions = model.predict(x)
# print("预测值:", predictions)

[1 2 3 4 5]
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]


## 赫斯特（Hurst）指数
赫斯特（Hurst）指数是一种用于分析时间序列数据的统计工具，主要用于衡量时间序列的长期记忆性或自相关性。赫斯特指数是由英国水文学家哈罗德·赫斯特（Harold Edwin Hurst）在20世纪50年代提出的，最初用于分析尼罗河的水位变化。

赫斯特指数的取值范围在0到1之间，可以分为以下几种情况：

H = 0.5：时间序列是随机的，没有自相关性。这种情况下，时间序列的未来值与过去值之间没有任何关系。

0.5 < H < 1：时间序列具有长期记忆性，即未来的趋势与过去的趋势有关。这种情况下，时间序列呈现出持久性（persistence），即如果过去是上升的，未来也很可能继续上升；如果过去是下降的，未来也很可能继续下降。

0 ≤ H < 0.5：时间序列具有反记忆性（antipersistence），即未来的趋势与过去的趋势相反。这种情况下，时间序列呈现出均值回归（mean reversion）的特性，即如果过去是上升的，未来很可能下降；如果过去是下降的，未来很可能上升。

赫斯特指数的计算方法有很多种，其中最常用的是重标极差法（Rescaled Range Analysis, R/S）。以下是计算赫斯特指数的基本步骤：

1. 将时间序列分成若干个等长的子序列。
2. 对每个子序列计算累积和（cumulative sum）。
3. 对每个子序列计算标准差（standard deviation）。
4. 计算每个子序列的重标极差（rescaled range），即累积和的最大值与最小值之差除以子序列的标准差。
5. 计算整个时间序列的重标极差均值。
6. 根据重标极差均值和时间序列的长度计算赫斯特指数。

赫斯特指数在许多领域都有广泛的应用，如金融市场分析、气象学、水文学、地球物理学等。通过计算赫斯特指数，可以帮助我们了解时间序列数据的特性，预测未来趋势，以及评估不同时间序列之间的相关性。

方差比检验（Variance Ratio Test）是一种用于检验两个或多个独立样本方差是否相等的统计方法。它基于F分布，通过比较两组数据的方差来判断它们是否来自具有相同方差的总体。

方差比检验的步骤如下：

提出假设：

原假设（H0）：两组数据的方差相等。
备择假设（H1）：两组数据的方差不等于相等。
计算检验统计量：

计算两组数据的样本方差 ( s_1^2 ) 和 ( s_2^2 )。
计算方差比 ( VR = \frac{s_1^2}{s_2^2} ) 或 ( VR = \frac{s_2^2}{s_1^2} )，具体取决于哪组数据的方差较大。
根据样本大小 ( n_1 ) 和 ( n_2 )，查找F分布表，确定临界值 ( F_{\alpha/2} ) 和 ( F_{1-\alpha/2} )。
做出决策：

如果 ( VR ) 落在拒绝域内（即 ( VR < F_{\alpha/2} ) 或 ( VR > F_{1-\alpha/2} )），则拒绝原假设，认为两组数据的方差不等于相等。
如果 ( VR ) 落在接受域内，则不拒绝原假设，认为两组数据的方差相等。
方差比检验的适用条件包括：

样本是独立的。
样本来自正态分布的总体。
方差比检验通常用于比较两个独立样本的方差，但也可以扩展到多个样本的情况。
需要注意的是，方差比检验对样本大小和分布的正态性有一定的要求。如果样本大小较小或数据分布偏离正态性，检验结果可能不准确。在实际应用中，可以考虑使用其他统计方法，如Levene检验或Bartlett检验，来检验方差的齐性。

半衰期检验（Half-Life Test）是一种用于评估放射性物质衰变速率的实验方法。在核物理学、化学和环境科学等领域，半衰期检验被广泛应用于研究放射性同位素的衰变特性。通过测量放射性物质在一定时间内的衰变量，可以计算出其半衰期，从而了解其衰变速率和放射性强度。

半衰期检验的基本原理是：在一个封闭系统中，放射性物质的原子核会随着时间的推移逐渐衰变成其他元素或同位素。在衰变过程中，放射性物质的剩余量会按照一定的规律减少。半衰期是指放射性物质剩余量减少到原来的一半所需的时间。

进行半衰期检验的步骤如下：

准备样品：选择一个合适的放射性物质样品，并将其置于一个封闭的容器中。

测量初始放射性强度：使用辐射探测器测量样品的初始放射性强度。

等待一段时间：等待足够长的时间，使得样品的放射性强度发生明显变化。

再次测量放射性强度：在等待时间结束后，再次使用辐射探测器测量样品的放射性强度。

计算半衰期：根据两次测量的放射性强度和时间间隔，使用以下公式计算半衰期：

[ t_{1/2} = \frac{\ln(2)}{k} ]

其中，( t_{1/2} ) 是半衰期，( \ln(2) ) 是自然对数的底数（约等于 0.693），( k ) 是衰变速率常数。

分析结果：根据计算出的半衰期，分析放射性物质的衰变速率和放射性强度。

需要注意的是，半衰期检验需要在专业的实验室环境中进行，并采取适当的安全措施，以防止辐射对人体的伤害。此外，半衰期检验的结果可能受到测量误差和其他因素的影响，因此需要进行多次实验并取平均值以提高准确性。

**半衰期检验（Half-Life Test）本身并不是专门用于测试时间序列的回归性和平稳性的方法。半衰期检验主要用于评估放射性物质衰变速率，而不是时间序列分析**

协整型ADF检验（Cointegration Augmented Dickey-Fuller Test）是一种用于检验两个或多个非平稳时间序列是否存在协整关系的统计方法。协整关系指的是两个或多个时间序列之间存在长期的稳定关系，即使它们各自是非平稳的。

在进行协整型ADF检验之前，通常需要先对时间序列进行单位根检验，以确定它们是否为非平稳的。如果两个时间序列都是非平稳的，但它们的线性组合是平稳的，那么这两个时间序列之间存在协整关系。

协整型ADF检验的基本步骤如下：

单位根检验：首先对两个或多个时间序列分别进行单位根检验，确定它们是否为非平稳的。常用的单位根检验方法有 Augmented Dickey-Fuller (ADF) 检验和 Phillips-Perron (PP) 检验。

估计协整关系：如果两个时间序列都是非平稳的，接下来需要估计它们之间的协整关系。这可以通过最小二乘法或其他回归方法来实现。

协整型ADF检验：在估计出协整关系后，进行协整型ADF检验。这个检验实际上是检验残差序列是否平稳。如果残差序列是平稳的，那么两个时间序列之间存在协整关系；否则，它们之间不存在协整关系。

解释结果：根据协整型ADF检验的结果，可以得出两个时间序列之间是否存在协整关系的结论。如果存在协整关系，那么可以利用这个关系进行预测和分析。

需要注意的是，协整型ADF检验对样本大小和数据质量有一定的要求。如果样本太小或数据存在严重的自相关或异方差问题，检验结果可能不准确。在实际应用中，可以考虑使用其他协整检验方法，如 Engle-Granger 两步法或 Johansen 协整检验。

In [16]:
import numpy as np
import pandas as pd
from statsmodels.tsa.stattools import adfuller
from statsmodels.regression.linear_model import OLS

# 生成两个非平稳的时间序列
np.random.seed(42)
n = 100
x = np.cumsum(np.random.randn(n))
y = 2 * x + np.cumsum(np.random.randn(n))

# 单位根检验
result_x = adfuller(x)
result_y = adfuller(y)

print("x 的单位根检验结果：", result_x)
print("y 的单位根检验结果：", result_y)

# 估计协整关系
model = OLS(y, x).fit()
residuals = model.resid

# 协整型ADF检验
result_residuals = adfuller(residuals)

print("残差序列的单位根检验结果：", result_residuals)

# 解释结果
alpha = 0.05
if result_x[1] > alpha and result_y[1] > alpha and result_residuals[1] < alpha:
    print("x 和 y 存在协整关系")
else:
    print("x 和 y 不存在协整关系")

x 的单位根检验结果： (-1.3583317659818985, 0.6020814791099101, 0, 99, {'1%': -3.498198082189098, '5%': -2.891208211860468, '10%': -2.5825959973472097}, 222.8689980232281)
y 的单位根检验结果： (-1.258001500815765, 0.6481611011736785, 1, 98, {'1%': -3.4989097606014496, '5%': -2.891516256916761, '10%': -2.5827604414827157}, 356.0626708213774)
残差序列的单位根检验结果： (-1.9559190170990346, 0.3062290299375441, 0, 99, {'1%': -3.498198082189098, '5%': -2.891208211860468, '10%': -2.5825959973472097}, 237.03854879262025)
x 和 y 不存在协整关系
